
spring:
  config:
    import: optional:certs/config.properties
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  application:
    name: bookStore



rsa:
  rsaPrivateKey: ${RSA_PRIVATE_KEY}
  rsaPublicKey: ${RSA_PUBLIC_KEY}

server:
  port: 8081

file:
  directory: src/main/resources/uploaded-books

monnify:
  key: ${MONNIFY_KEY}
  secrete: ${MONNIFY_SECRETE}